module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        "gray-500": "var(--gray-500)",
        "gray-900": "var(--gray-900)",
        "light-themetextsecondary-body": "var(--light-themetextsecondary-body)",
        "neutral-100": "var(--neutral-100)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "neutral-600": "var(--neutral-600)",
        "neutral-800": "var(--neutral-800)",
        "neutral-colors-100": "var(--neutral-colors-100)",
        "neutral-colors-800": "var(--neutral-colors-800)",
        "primarycolor-2": "var(--primarycolor-2)",
        "primarycolor-3": "var(--primarycolor-3)",
        "secondary-colors-color-2": "var(--secondary-colors-color-2)",
        darktextprimary: "var(--darktextprimary)",
        "greylight-1": "var(--greylight-1)",
        lightactionactive: "var(--lightactionactive)",
        lightbackgroundtransparent: "var(--lightbackgroundtransparent)",
        lightothersdivider: "var(--lightothersdivider)",
        lighttextprimary: "var(--lighttextprimary)",
        lighttextsecondary: "var(--lighttextsecondary)",
        lighttextdisabled: "var(--lighttextdisabled)",
        primarymain: "var(--primarymain)",
        "secondary-5-workdlight": "var(--secondary-5-workdlight)",
        "secondary-7-workddark": "var(--secondary-7-workddark)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "paragraph-default": "var(--paragraph-default-font-family)",
        "text-single-200-regular": "var(--text-single-200-regular-font-family)",
        "text-single-300-bold": "var(--text-single-300-bold-font-family)",
        "BTN-l-semi-bold": "var(--BTN-l-semi-bold-font-family)",
        "BTN-m-semi-bold": "var(--BTN-m-semi-bold-font-family)",
        "h4-medium": "var(--h4-medium-font-family)",
        "h5-medium": "var(--h5-medium-font-family)",
        "p-body-m-medium": "var(--p-body-m-medium-font-family)",
        "p-body-s-regular": "var(--p-body-s-regular-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
